# Permalinks
permalink:           pretty

# Setup
title:               vidyaly
tagline:             a blog covering science, renewable energy, and our changing climate
url:                 https://vidyaly.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Vidya Ganapati
  url:               https://vidyaly.github.io
  email:             vidyaly2016@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/vidyaly/vidyaly.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive'}